import { TechStackConfig } from './types';

export const techStackConfig: TechStackConfig = {
  titlePrefix: "Engineered With The World's ",
  titleHighlight: 'BEST',
  titleSuffix: ' Toolchain',
  subtitle:
    'Every production system is built upon the most robust, enterprise-grade, and performant technologies. No debt, no friction from day one.',
  categories: [
    { id: 'all', label: 'All Technologies' },
    { id: 'ai', label: 'AI & Intelligence' },
    { id: 'frontend', label: 'Frontend & 3D' },
    { id: 'backend', label: 'Backend & Data' },
    { id: 'devops', label: 'Cloud & Infrastructure' },
  ],
  items: [
    // Row 1 (Frontend, AI, Modern Fullstack)
    {
      id: 'nextjs',
      name: 'Next.js 15',
      category: 'frontend',
      categoryLabel: 'Fullstack Framework',
      description: 'Production React framework with App Router, SSR & Turbopack streaming.',
      brandColor: '#FFFFFF',
      row: 1,
      iconName: 'nextjs',
    },
    {
      id: 'typescript',
      name: 'TypeScript',
      category: 'frontend',
      categoryLabel: 'Language',
      description: 'Strict static typing delivering zero-runtime surprises across all micro-services.',
      brandColor: '#3178C6',
      row: 1,
      iconName: 'typescript',
    },
    {
      id: 'react',
      name: 'React 19',
      category: 'frontend',
      categoryLabel: 'UI Library',
      description: 'Declarative component architecture powered by Server Actions and concurrent mode.',
      brandColor: '#61DAFB',
      row: 1,
      iconName: 'react',
    },
    {
      id: 'openai',
      name: 'OpenAI API',
      category: 'ai',
      categoryLabel: 'LLMs & Vision',
      description: 'Advanced reasoning, embeddings, and real-time multimodal intelligence integrations.',
      brandColor: '#10A37F',
      row: 1,
      iconName: 'openai',
    },
    {
      id: 'claude',
      name: 'Anthropic Claude',
      category: 'ai',
      categoryLabel: 'Agentic Reasoning',
      description: 'High-context agent orchestration, code analysis, and deterministic tool use.',
      brandColor: '#D97757',
      row: 1,
      iconName: 'claude',
    },
    {
      id: 'tailwind',
      name: 'Tailwind CSS',
      category: 'frontend',
      categoryLabel: 'Design System',
      description: 'Utility-first modern styling system built for high-velocity UI iteration.',
      brandColor: '#06B6D4',
      row: 1,
      iconName: 'tailwind',
    },
    {
      id: 'python',
      name: 'Python',
      category: 'backend',
      categoryLabel: 'AI & Backend',
      description: 'Core backbone for machine learning models, async workers, and vector pipelines.',
      brandColor: '#3776AB',
      row: 1,
      iconName: 'python',
    },
    {
      id: 'supabase',
      name: 'Supabase',
      category: 'backend',
      categoryLabel: 'Serverless Backend',
      description: 'Postgres with instant Row-Level Security, Edge Functions, and vector search.',
      brandColor: '#3ECF8E',
      row: 1,
      iconName: 'supabase',
    },
    {
      id: 'threejs',
      name: 'Three.js / WebGL',
      category: 'frontend',
      categoryLabel: '3D Graphics',
      description: 'GPU-accelerated interactive 3D globes, shaders, and real-time canvas visualizations.',
      brandColor: '#FFFFFF',
      row: 1,
      iconName: 'threejs',
    },
    {
      id: 'pinecone',
      name: 'Pinecone',
      category: 'ai',
      categoryLabel: 'Vector Database',
      description: 'Sub-millisecond semantic search index for production RAG pipelines.',
      brandColor: '#10B981',
      row: 1,
      iconName: 'pinecone',
    },
    {
      id: 'langchain',
      name: 'LangChain',
      category: 'ai',
      categoryLabel: 'Agent Framework',
      description: 'Composable abstractions for autonomous AI agents, tool routing, and memory.',
      brandColor: '#22C55E',
      row: 1,
      iconName: 'langchain',
    },
    {
      id: 'vercel',
      name: 'Vercel',
      category: 'devops',
      categoryLabel: 'Edge Deployment',
      description: 'Instant global CDN caching, zero-cold-start edge compute, and preview branches.',
      brandColor: '#FFFFFF',
      row: 1,
      iconName: 'vercel',
    },
    {
      id: 'redis',
      name: 'Redis',
      category: 'backend',
      categoryLabel: 'In-Memory Store',
      description: 'Sub-millisecond caching, rate-limiting, and distributed pub/sub event bus.',
      brandColor: '#DC382D',
      row: 1,
      iconName: 'redis',
    },
    {
      id: 'graphql',
      name: 'GraphQL',
      category: 'backend',
      categoryLabel: 'API Query Layer',
      description: 'Strongly typed client-driven data fetching with fine-grained resolver control.',
      brandColor: '#E535AB',
      row: 1,
      iconName: 'graphql',
    },

    // Row 2 (Backend, Infrastructure, DevOps, Cloud)
    {
      id: 'vite',
      name: 'Vite',
      category: 'frontend',
      categoryLabel: 'Build Tooling',
      description: 'Lightning-fast native ES modules bundling and instant HMR dev experience.',
      brandColor: '#BD34FE',
      row: 2,
      iconName: 'vite',
    },
    {
      id: 'docker',
      name: 'Docker',
      category: 'devops',
      categoryLabel: 'Containerization',
      description: 'Reproducible multi-stage container builds ensuring parity across all environments.',
      brandColor: '#2496ED',
      row: 2,
      iconName: 'docker',
    },
    {
      id: 'postgresql',
      name: 'PostgreSQL',
      category: 'backend',
      categoryLabel: 'Relational DB',
      description: 'ACID-compliant battle-tested relational database with pgvector extensions.',
      brandColor: '#4169E1',
      row: 2,
      iconName: 'postgresql',
    },
    {
      id: 'kubernetes',
      name: 'Kubernetes',
      category: 'devops',
      categoryLabel: 'Orchestration',
      description: 'Auto-scaling container workloads, self-healing rollouts, and zero-downtime service mesh.',
      brandColor: '#326CE5',
      row: 2,
      iconName: 'kubernetes',
    },
    {
      id: 'aws',
      name: 'AWS Cloud',
      category: 'devops',
      categoryLabel: 'Cloud Infrastructure',
      description: 'Resilient high-availability cloud architecture (S3, ECS, Lambda, CloudFront).',
      brandColor: '#FF9900',
      row: 2,
      iconName: 'aws',
    },
    {
      id: 'nodejs',
      name: 'Node.js',
      category: 'backend',
      categoryLabel: 'Runtime',
      description: 'Non-blocking event-driven backend microservices and streaming pipelines.',
      brandColor: '#5FA04E',
      row: 2,
      iconName: 'nodejs',
    },
    {
      id: 'github',
      name: 'GitHub Actions',
      category: 'devops',
      categoryLabel: 'CI / CD',
      description: 'Automated test suites, security vulnerability auditing, and seamless deployments.',
      brandColor: '#F0F6FC',
      row: 2,
      iconName: 'github',
    },
    {
      id: 'kafka',
      name: 'Apache Kafka',
      category: 'backend',
      categoryLabel: 'Event Streaming',
      description: 'High-throughput distributed event streaming for audit logs and asynchronous queues.',
      brandColor: '#E84335',
      row: 2,
      iconName: 'kafka',
    },
    {
      id: 'prisma',
      name: 'Prisma ORM',
      category: 'backend',
      categoryLabel: 'Type-Safe ORM',
      description: 'Next-generation object-relational mapping with automated migrations and type inference.',
      brandColor: '#5A67D8',
      row: 2,
      iconName: 'prisma',
    },
    {
      id: 'stripe',
      name: 'Stripe API',
      category: 'backend',
      categoryLabel: 'Payments & Billing',
      description: 'Secure payment gateway, recurring subscriptions, and webhook reconciliation.',
      brandColor: '#635BFF',
      row: 2,
      iconName: 'stripe',
    },
    {
      id: 'bun',
      name: 'Bun',
      category: 'backend',
      categoryLabel: 'High-Speed Runtime',
      description: 'Blazing fast JavaScript & TypeScript runtime with built-in SQLite and package manager.',
      brandColor: '#FBF0DF',
      row: 2,
      iconName: 'bun',
    },
    {
      id: 'pytorch',
      name: 'PyTorch',
      category: 'ai',
      categoryLabel: 'Deep Learning',
      description: 'Tensors and dynamic neural networks for fine-tuning embeddings and LLM adapters.',
      brandColor: '#EE4C2C',
      row: 2,
      iconName: 'pytorch',
    },
    {
      id: 'cloudflare',
      name: 'Cloudflare',
      category: 'devops',
      categoryLabel: 'DDoS & Workers',
      description: 'Global edge DNS, WAF security protection, and distributed edge KV storage.',
      brandColor: '#F38020',
      row: 2,
      iconName: 'cloudflare',
    },
    {
      id: 'linux',
      name: 'Linux / Unix',
      category: 'devops',
      categoryLabel: 'Core OS',
      description: 'Hardened kernel performance, systemd daemon management, and network tuning.',
      brandColor: '#FCC624',
      row: 2,
      iconName: 'linux',
    },
  ],
};
